import Head from 'next/head'
import { useState } from "react"
import styles from '@/styles/Home.module.css'
import { FiPlusCircle } from "react-icons/fi"

import CreateEvent from '@/components/CreateEvent'
import JoinEvent from '@/components/JoinEvent'

import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [createpage, setCreatePage] = useState(false);
  const [joinpage, setJoinPage] = useState(false);

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

        <main className={styles.main}>
          <div className={styles.navbar}>
            <div></div>
            <input type="text" />
          </div>

          <div className={styles.titlebox}>
            <h4>My events</h4>
            <FiPlusCircle className={styles.addbtns} onClick={() => setCreatePage(true)}/>

          </div>
          <div className={styles.events}>
            <div>
              <p>Event A</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event B</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event C</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event D</p>
              <p>ID number</p>
            </div>
          </div>

          <div className={styles.titlebox}>
            <h4>Events I have joined</h4>
            <FiPlusCircle className={styles.addbtns} onClick={() => setJoinPage(true)}/>
          </div>
          <div className={styles.events}>
            <div>
              <p>Event A</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event B</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event C</p>
              <p>ID number</p>
            </div>
            <div>
              <p>Event D</p>
              <p>ID number</p>
            </div>
          </div>

          <CreateEvent isOpen={createpage} close={ setCreatePage }/>
          <JoinEvent isOpen={joinpage} close={ setJoinPage }/>

        </main>



      
    </>
  )
}
