import Head from 'next/head'
import Link from 'next/link'
import { useState } from "react"
import styles from '@/styles/Home.module.css'
import { FiPlusCircle } from "react-icons/fi"

import Logo from '@/components/Logo'
import CreateEvent from '@/components/CreateEvent'
import SearchEvent from '@/components/SearchEvent'

import GetUserEvents from '@/utils/GetUserEvents'

import { signOut } from 'firebase/auth'
import { auth } from '@/firebase'

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [createpage, setCreatePage] = useState(false);
  const [joinpage, setJoinPage] = useState(false);

  const userEvents = GetUserEvents();

  const showUserEvents = () => {
    return (
      userEvents?.map(
            event => 
            <Link key={Math.random()} href={`/events/${event.id}`} className={styles.eventlink}>
              <p>{event.name}</p>
              <p>{event.id}</p>
            </Link>
        )
    )
}

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

        <main className={styles.main}>
          <div className={styles.navbar}>
            <Logo />
            <input type="text" />
          </div>

          <div className={styles.titlebox}>
            <h4>My events</h4>
            <FiPlusCircle className={styles.addbtns} onClick={() => setCreatePage(true)}/>
          </div>
          <div className={styles.events}>
          
            { showUserEvents() }
            
          </div>

          <div className={styles.titlebox}>
            <h4>Events I have joined</h4>
            <FiPlusCircle className={styles.addbtns} onClick={() => setJoinPage(true)}/>
          </div>

          <div className={styles.events}>

            <Link href="/JoinedEventPage" className={styles.eventlink}>
              <p>Event A</p>
              <p>ID number</p>
            </Link>
            <Link href="/JoinedEventPage" className={styles.eventlink}>
              <p>Event A</p>
              <p>ID number</p>
            </Link>
            <Link href="/JoinedEventPage" className={styles.eventlink}>
              <p>Event A</p>
              <p>ID number</p>
            </Link>
            <Link href="/JoinedEventPage" className={styles.eventlink}>
              <p>Event A</p>
              <p>ID number</p>
            </Link>

          </div>

          <button onClick={ () => signOut(auth)}>SignOut</button>


          <CreateEvent isOpen={createpage} close={ setCreatePage }/>
          <SearchEvent isOpen={joinpage} close={ setJoinPage }/>

        </main>



      
    </>
  )
}
